name: Test SSH Connection
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Key
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Check Port 22
        run: |
          nc -zv ${{ secrets.SERVER_IP }} 22 || echo "Port 22 is CLOSED or unreachable"

      - name: SSH Keyscan
        run: |
          ssh-keyscan -p 22 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts 2>&1 || echo "keyscan failed"

      - name: Test SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
              "echo 'Connected '"
