name: Test SSH Connection
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Key
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug IP
        run: |
          echo "IP length: ${#SERVER_IP}"
          echo "IP is: [${{ secrets.SERVER_IP }}]"

      - name: SSH Keyscan
        run: |
          ssh-keyscan -v -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "echo 'Connected '"
